

services:
  db:
    image: mysql:8.0
    entrypoint: 
      - MYSQL_DATABASE=TODO
      - MYSQL_ROOT_PASSWORD=lolminhga67 
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

      
volumes:
  db:
    driver: local